### PR TITLE
App state

### PR DESCRIPTION
**Pull request by akesson**
To me, the holy grail is having the state in a separate, testable crate. That is directly testable, without rendering HTML. In other words, the business logic separated from the UI.

This is an attempt to achieve this. Have a look at `examples/app-state/src/state.rs` to see what I mean. 

For some reason, the `spawn_local` doesn't work for the tests, see ce5b8d8. I did a workaround for it in 430edfd. Would you have an idea of why?

If you like this, then the `drive.rs` could move to the `silkenweb/package/signals-ext` crate and should probably have more variants added to `drive_...`. Maybe even be written as a `trait` so that it can be used directly on a signal: 
```rust
let counter: Mutable<isize> = Mutable::new(0);
let text: Mutable<String> = counter.signal().map(|v| format!("Value: {v}").drive_value();
```

The `test_utilities.rs` should move somewhere else as well so that they can be reused.

I'd love some of your feedback on this.

### CODE REVIEW

**Comment by simon-bourne** [comment]
Some initial thoughts on `drive_value` and `drive_vector`:

- `drive_value` seems like a good primitive. I'd really like to get rid of `start_value` though. I'm sure the contract for signals say they must have an initial value. Maybe we could `poll` it once and require it to be ready. What do the `futures-signals` docs say?
- I'm not sure about `drive_vector`. I think a better primitive might be something like `fn spawn_for_each<T>(sig: impl Signal<Item = T>, f: impl FnMut(T))`.

I like the idea of a `trait`, with methods that integrate with the Silkenweb task queue.

I'll take a look at `test_utils` next.

**Comment by simon-bourne** [comment]
I think your problems with `spawn_local` might be because you're not calling `render_now`. It's kind of like `tokio::task::yield_now`, except provides more guarantees. `render_now` isn't a great name, I must admit!

I don't think `tokio::task::yield_now` provides enough guarantees for what you're using it for. What if a signal doesn't complete in a single `poll` for example. I might be wrong though, haven't thought about it enough.

Also, I wonder if you could use `SignalExt::to_stream` to get rid of the `start_value` in `drive_value`?

**Comment by akesson** [comment]
Thanks for the feedback. I'm leaving on holiday for a week now and will have a look at the end of the following week.

**Comment by simon-bourne** [comment]
I had a bit more of a think about this, and played around with your example. I like your idea of a trait, and I guess the theme would be "methods for signals that require a runtime". So `drive`, and a `spawn_for_each` (like `SigValue::new` but without the yield). Something like:

```rust
trait TaskSignal<T>: Signal<Item = T> + Sized {
    fn drive(self) -> Option<ReadOnlyMutable<T>>;

    fn spawn_for_each(self, f: impl FnMut(T));
}
```

That would let you write your example in `state.rs` similarly, but with a few `render_now().await;` calls. `drive` should return an `Option` because it could fail if the signal is finished. Also, I think `drive` should probably be called `to_mutable` or `into_mutable` to avoid introducing another term.

**Comment by akesson** [comment]
Great feedback!

I updated the code to use traits, have a look. I also use some naming that you should see as a proposal. Insist on your own naming and I'll give in to it ;)

> "methods for signals that require a runtime"

Yay. That sums it up very well. One of my wishes is to avoid a full silkenweb dependency for the state handling because that makes it possible to mix in UI & HTML stuff into the business logic. What would you think about refactoring silkenweb so that all runtime-related code ends up in a `silkenweb-runtime` crate? Like that, the stuff I'm doing here could end up in that crate as well and it could use the `silkenweb_runtime::render_now` and `silkenweb_runtime::spawn_local`.


> I don't think tokio::task::yield_now provides enough guarantees for what you're using it for.

I think you are right and that there are two options:
1. Write a [custom Executor](https://rust-lang.github.io/async-book/02_execution/04_executor.html) that provides a `yield_until_all_idle` function. Quite a bit of work.
2. Add a comment to `SigValue.get` and `VecValue.get` saying that you might need to call `render_now` a few times for state that have nested driven mutables.

I propose to go for 2. until we have a real-world example of the problem.


> I'd really like to get rid of `start_value` though.

Me too. But I'm not sure how. Both Signal's `poll_change` and Stream's `poll_next` takes a `cx: &mut Context<'_>` argument.

**Comment by akesson** [comment]
> I think your problems with spawn_local might be because you're not calling render_now. It's kind of like tokio::task::yield_now, except provides more guarantees.

Yes, you were right

**Comment by akesson** [comment]
I moved the app state traits to the silkenweb crate, but I hope that's just temporary. C.f #65

**Comment by simon-bourne** [comment]
Sorry for the delay in replying, but I've been away on holiday.

> I updated the code to use traits, have a look. I also use some naming that you should see as a proposal. Insist on your own naming and I'll give in to it ;)

Looks good, but I'm not keen on the `to_mutable_vec` method. Signals are lossy and allowed to discard intermediate values. I think a `spawn_for_each` method is much more general and less confusing. This makes the `SignalToMutable` name less relevant, but I'm also not wedded to `TaskSignal` so open to suggestions!

> 
> > "methods for signals that require a runtime"
> 
> Yay. That sums it up very well. One of my wishes is to avoid a full silkenweb dependency for the state handling because that makes it possible to mix in UI & HTML stuff into the business logic. What would you think about refactoring silkenweb so that all runtime-related code ends up in a `silkenweb-runtime` crate? Like that, the stuff I'm doing here could end up in that crate as well and it could use the `silkenweb_runtime::render_now` and `silkenweb_runtime::spawn_local`.
> 

That sounds like a great idea. It does need some thought, particularly around `TaskLocal` and `server::scope`.

> > I don't think tokio::task::yield_now provides enough guarantees for what you're using it for.
> 
> I think you are right and that there are two options:
> 
>     1. Write a [custom Executor](https://rust-lang.github.io/async-book/02_execution/04_executor.html) that provides a `yield_until_all_idle` function. Quite a bit of work.

`render_now` already does exactly this.

> > I'd really like to get rid of `start_value` though.
> 
> Me too. But I'm not sure how. Both Signal's `poll_change` and Stream's `poll_next` takes a `cx: &mut Context<'_>` argument.

I had a quick play around and you can do this:

```rust
pub async fn try_to_mutable<T>(s: impl Signal<Item = T> + 'static) -> Option<ReadOnlyMutable<T>>
where
    T: Clone + 'static,
{
    let mut s = Box::pin(s.to_stream());
    let first_value = s.next().await?;
    let result = Mutable::new(first_value);

    spawn_local({
        clone!(result);
        async move {
            while let Some(value) = s.next().await {
                result.set(value);
            }
        }
    });

    Some(result.read_only())
```

It does make the function `async`, so you'd need to use the `async-trait` crate to make this a trait method. You could add a `to_mutable` that unwraps the option if you want.

> I moved the app state traits to the silkenweb crate, but I hope that's just temporary. C.f #65

I think `SignalToMutable` belongs in a `runtime` module. I'm not keen on the `SigValue`/`VecValue` structs. `SigValue` can be replaced with a `ReadOnlyMutable` (via `.to_mutable`) and a call to `render_now`. Another trait for `SignalVec`s with `.to_mutable` would allow you to do the same for `VecValue`

**Comment by akesson** [comment]
> Sorry for the delay in replying, but I've been away on holiday.

No problem. I hope you had a great holiday!

> Looks good, but I'm not keen on the `to_mutable_vec` method. Signals are lossy and allowed to discard intermediate values. I think a `spawn_for_each` method is much more general and less confusing. This makes the `SignalToMutable` name less relevant, but I'm also not wedded to `TaskSignal` so open to suggestions!

Ok, changed it to `spawn_for_each` and `TaskSignal` (I don't really have any good ideas).

> `render_now` already does exactly this.

I changed so that you have to use `render_now` in the tests instead.

> I think `SignalToMutable` belongs in a runtime module. I'm not keen on the `SigValue`/`VecValue` structs. `SigValue` can be replaced with a `ReadOnlyMutable` (via .to_mutable) and a call to render_now. Another trait for `SignalVecs` with `.to_mutable` would allow you to do the same for `VecValue`

Let's add this to the silkenweb crate for now and as soon as it is merged, I'll (we'll?) start looking at how to extract a runtime crate.

I did most of the changes you proposed, but the `to_value.rs` (didn't yet rename it in order to keep it easier to review) `.to_value` for `SignalVec` is a bit tricky as the [MutableVecLockMut](https://docs.rs/futures-signals/0.3.32/futures_signals/signal_vec/struct.MutableVecLockMut.html) requires `Clone ` or `Copy` for many of the necessary operations. I also didn't find a good way to get the first value. See 2e681b8.

--- 

It is starting to look good. Once we get these last things sorted I'll add documentation and some unit testing.

**Comment by simon-bourne** [comment]
Also, we can remove `TSig` from the `TaskSignal` trait, and just use `Self::Item` instead.

**Comment by akesson** [comment]
From what I can see, a [Mutable](https://docs.rs/futures-signals/0.3.32/futures_signals/signal/struct.Mutable.html) cannot be created without a value and the doc for [to_stream](https://docs.rs/futures-signals/0.3.32/futures_signals/signal/trait.SignalExt.html#method.to_stream) says _"It immediately outputs the current value of self"_. Wouldn't that mean that the try_to_mutable is not necessary as we could do `s.next().await.unwrap()`?

---

> - spawn_for_each should be a really simple wrapper around for_each, something like:
> ```rust
> fn spawn_for_each(self, mut f: impl FnMut(T) + 'static) {
>    spawn_local(self.for_each(move |value| {
>        f(value);
>        async {}
>    }));
> }
> ```

Hm, I'm not sure I follow you. How would that be used? I mean, from where I stand, the idea is to make it possible to create a MutableVec based on the values of a Mutable. From the [CounterState](https://github.com/akesson/silkenweb/blob/app-state/examples/app-state/src/state.rs#L23):
```rust
        let count = Mutable::new(0);
        let list = count
            .signal()
            .spawn_for_each(|vec, value| vec.lock_mut().push(value));
```

**Comment by akesson** [comment]
Thanks for the explanation. I think the issue here is that I have a contrived example in `State.rs` which creates an unrealistic necessity of driving a MutableVec from a Mutable. 

What would you think about keeping this PR to only the `Signal.to_mutable` and `SignalVec.to_mutable`?

**Comment by simon-bourne** [comment]
> What would you think about keeping this PR to only the `Signal.to_mutable` and `SignalVec.to_mutable`?

Yes, that's a good idea.

**Comment by simon-bourne** [comment]
I've merged this into the `signals-runtime` branch, and will make a few changes before merging into `main`. Thanks for all the work so far!

**Comment by akesson** [comment]
Well, thank you for your patience and feedback!

**Pull request merged**
